[package]
name = "modernpro-coverletter"
version = "0.0.3"
entrypoint = "modernpro-coverletter.typ"
authors = [ "academic-template-collective",]
repository = "https://example.invalid/academic-templates/modernpro-coverletter"
license = "MIT"
description = "A cover letter template with modern Sans font for job applications and other formal letters."
keywords = [ "coverletter", "CV", "Job",]
categories = [ "cv", "utility",]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
